name: Release
on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '.changeset/**'
      - '.github/workflows/release.yml'
env:
  HUSKY: 0 # Bypass husky commit hook for CI
jobs:
  version:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1
          run_install: true

      - name: Copy README file to React package
        uses: canastro/copy-file-action@master
        with:
          source: 'README.md'
          target: 'packages/react/README.md'

      - name: Copy README file to Vanilla package
        uses: canastro/copy-file-action@master
        with:
          source: 'README.md'
          target: 'packages/vanilla/README.md'

      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@v1
        # if: github.ref == 'refs/heads/master'
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          # Messages
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
        env:
          # npm publish token required for publishing. Set this in secrets
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # automatically available in actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
